/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mateUruguasho2.gltf --transform 
Files: mateUruguasho2.gltf [927.73KB] > mateUruguasho2-transformed.glb [291.4KB] (69%)
Author: pixol3d (https://sketchfab.com/pixol3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mate-3d-bfc8b17031da4f60ade142583e9793b5
Title: MATE 3D
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/mateUruguasho2-transformed.glb");
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.FRENTE_MATE}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["FRENTE_MATE.1"]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.METAL}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.YERBA}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials["METAL.2"]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/mateUruguasho2-transformed.glb");
