/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 matesuli.gltf --transform 
Files: matesuli.gltf [39.01MB] > matesuli-transformed.glb [2.51MB] (94%)
Author: Ermolli (https://sketchfab.com/ermolli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mate-uruguayo-e2fd6553b7b144f8afe2dc51929f95a3
Title: Mate Uruguayo.
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/matesuli-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.MateFull}
      />
      <mesh
        geometry={nodes.defaultMaterial_1.geometry}
        material={materials.MateFull1}
      />
      <mesh
        geometry={nodes.defaultMaterial_2.geometry}
        material={materials.MateFull2}
      />
      <mesh
        geometry={nodes.defaultMaterial_3.geometry}
        material={materials.MateFull3}
      />
    </group>
  );
}

useGLTF.preload("/matesuli-transformed.glb");
