/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 computer.gltf 
Author: Valger (https://sketchfab.com/Valger)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/a-personal-computer-54a9a7c2faf441c980b0ff07299431cd
Title: A personal computer.
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./computer.gltf");
  return (
    <group {...props} dispose={null} scale={0.01}>
      <group>
        <group
          position={[60.166, 176.449, -22.069]}
          rotation={[0, 0.175, 0]}
          scale={9.582}
        >
          <mesh
            geometry={nodes.left_monitor_Material__36_0.geometry}
            material={materials.Material__36}
          />
          <mesh
            geometry={nodes.left_monitor_Material__37_0.geometry}
            material={materials.Material__37}
          />
        </group>
        <group
          position={[-238.667, 6.08, -39.382]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={9.582}
        >
          <mesh
            geometry={nodes.tower_Material__38_0.geometry}
            material={materials.Material__38}
          />
          <mesh
            geometry={nodes.tower_Material__40_0.geometry}
            material={materials.Material__40}
          />
          <mesh
            geometry={nodes.tower_Material__45_0.geometry}
            material={materials.Material__45}
          />
          <mesh
            geometry={nodes.tower_Material__61_0.geometry}
            material={materials.Material__61}
          />
        </group>
        <group
          position={[525.99, 176.449, 36.573]}
          rotation={[0, -0.436, 0]}
          scale={9.582}
        >
          <mesh
            geometry={nodes.right_monitor_Material__37_0.geometry}
            material={materials.Material__37}
          />
          <mesh
            geometry={nodes.right_monitor_Material__59_0.geometry}
            material={materials.Material__59}
          />
        </group>
        <group
          position={[671.023, 60.358, 241.681]}
          rotation={[Math.PI / 2, 0, Math.PI / 6]}
          scale={2.346}
        >
          <mesh
            geometry={nodes.big_book_Material__82_0.geometry}
            material={materials.Material__82}
          />
          <mesh
            geometry={nodes.big_book_pages_0.geometry}
            material={materials.pages}
          />
        </group>
        <group
          position={[430.011, 0, 164.445]}
          rotation={[-Math.PI / 2, 0, 0.436]}
        >
          <mesh
            geometry={nodes.Box005_Material__64_0.geometry}
            material={materials.Material__64}
          />
          <mesh
            geometry={nodes.Box006_mouse_keys_0.geometry}
            material={materials.mouse_keys}
            position={[-14.832, 5.917, 7.032]}
            rotation={[0.029, -1.309, -1.456]}
          />
          <mesh
            geometry={nodes.Cylinder002_Material__65_0.geometry}
            material={materials.Material__65}
            position={[1.318, 13.291, 11.4]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
        <mesh
          geometry={nodes.left_monitor_leg_Material__39_0.geometry}
          material={materials.Material__39}
          position={[39.827, 0, -137.42]}
          rotation={[-Math.PI / 2, 0, 0.175]}
          scale={9.582}
        />
        <mesh
          geometry={nodes.right_monitor_leg_Material__39_0.geometry}
          material={materials.Material__39}
          position={[575.492, 0, -69.584]}
          rotation={[-Math.PI / 2, 0, -0.436]}
          scale={9.582}
        />
        <mesh
          geometry={nodes["web-cam_Material__42_0"].geometry}
          material={materials.Material__42}
          position={[57.1, 290.004, -39.457]}
          rotation={[0, 0.175, 0]}
          scale={9.582}
        />
        <mesh
          geometry={nodes.Sphere001_Material__43_0.geometry}
          material={materials.Material__43}
          position={[57.929, 289.718, -34.755]}
          rotation={[0, 0.175, 0]}
          scale={9.582}
        />
        <mesh
          geometry={nodes.pc_legs_Material__44_0.geometry}
          material={materials.Material__44}
          position={[-308.972, 2.099, 81.357]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={9.582}
        />
        <mesh
          geometry={nodes.keyboard_Material__57_0.geometry}
          material={materials.Material__57}
          position={[190.573, 2.526, 164.412]}
          rotation={[-1.507, 0, 0]}
          scale={9.582}
        />
        <mesh
          geometry={nodes["web-cam_leg_Material__41_0"].geometry}
          material={materials.Material__41}
          position={[60.551, 289.994, -42.673]}
          rotation={[0, -1.396, 0]}
          scale={9.582}
        />
        <mesh
          geometry={nodes.Box001_Material__63_0.geometry}
          material={materials.Material__63}
          position={[-254.79, 264.187, 96.305]}
        />
        <mesh
          geometry={nodes.Cylinder003_PC_logo_0.geometry}
          material={materials.PC_logo}
          position={[-207.951, 28.754, 94.411]}
        />
        <mesh
          geometry={nodes.Box004_Material__67_0.geometry}
          material={materials.Material__67}
          position={[-309.038, 28.765, 103.381]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/computer.gltf");
